apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisecow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/anupsharma329/wisecow-app.git
    targetRevision: main
    path: k8s
    # Let Argo CD detect and use kustomize (k8s/kustomization.yaml)
    # Do NOT use directory.recurse to avoid applying resources twice
  destination:
    server: https://kubernetes.default.svc
    namespace: wisecow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true

