apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-cert
  namespace: wisecow
spec:
  secretName: wisecow-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - wisecow.local
