name: Wisecow CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/wisecow-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # -------------------
      # CI: Build & Push
      # -------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # -------------------
      # CD: Deploy to K8s
      # -------------------
      - name: Set up kubectl
        if: ${{ secrets.KUBE_CONFIG != '' }}
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        if: ${{ secrets.KUBE_CONFIG != '' }}
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl cluster-info || echo "⚠️  Could not connect to cluster"

      - name: Update image in deployment
        run: |
          sed -i "s|image:.*|image: docker.io/${{ secrets.DOCKER_USERNAME }}/wisecow-app:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Deploy to Kubernetes
        if: ${{ secrets.KUBE_CONFIG != '' }}
        run: |
          echo "🚀 Deploying to Kubernetes..."
          kubectl apply -f k8s/namespace.yaml || true
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/wisecow-deployment -n wisecow --timeout=120s || echo "⚠️  Deployment failed or timed out"

      - name: Verify Deployment
        if: ${{ secrets.KUBE_CONFIG != '' }}
        run: |
          echo "📌 Deployment Status:"
          kubectl get pods -n wisecow || echo "⚠️  Could not get pods"
          kubectl get svc -n wisecow || echo "⚠️  Could not get services"

      - name: Skip Kubernetes Deployment
        if: ${{ secrets.KUBE_CONFIG == '' }}
        run: |
          echo "⚠️  Skipping Kubernetes deployment - KUBE_CONFIG secret not configured"
          echo "📝 To enable Kubernetes deployment, add your cluster config as KUBE_CONFIG secret" 
