name: Wisecow CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/wisecow-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # -------------------
      # CI: Build & Push
      # -------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # -------------------
      # CD: Update and Prepare
      # -------------------
      - name: Update image in deployment
        run: |
          sed -i "s|image:.*|image: docker.io/${{ secrets.DOCKER_USERNAME }}/wisecow-app:${{ github.sha }}|g" k8s/deployment.yaml
          echo "✅ Updated deployment.yaml with new image tag"

      - name: Build Complete
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "📦 Image: docker.io/${{ secrets.DOCKER_USERNAME }}/wisecow-app:${{ github.sha }}"
          echo "📝 Deployment file updated with new image tag"
          echo "🔧 For local deployment: kubectl apply -f k8s/" 
